name: buildauto
on: 
  push:
    branches: ["main"]
jobs:
  buildnow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with: 
        node-version: 20
    - name: build
      run: |
        npm install
        npm run build
        git config --global user.name "nut2334"
        git config --global user.email "nut2334@gmail.com"
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.TOKEN }}
        repository: ${{ github.repository }}